### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by jsimanjuntak** [aylei/aliyun-exporter#5]
Hi @aylei,

I have done setup the aliyun exporter and all its packages, but it ends up showing nothing on dashboard detail, but on dashboard overview, it only showing the running instance count and it shows the right numbers. 

I want to ask is this code will generate all the ecs/rds/redis on my aliyun console?

`      "targets": [`
`         {`
`          "expr": "sum(aliyun_meta_redis_info)",`
`          "format": "time_series",`
`         "intervalFactor": 1,`
`          "refId": "A"`
`        }`

any suggestions or is there some step got skipped maybe?

Thank you,

**Comment by aylei** [comment]
This query will return the number of your running cloud redis instances.

BTW, what does "but it ends up showing nothing on dashboard detail" mean? Could you please post a screenshot?

**Comment by jsimanjuntak** [comment]
I mean Dashboard-detail with your template, already got the solution, I have to create the dashboard manually.
Nothing is wrong with your repo, everything is good, my bad.

Thank you!
